 # MYSQL数据库配置
 DIALECT: 'mysql'
 DRIVER: 'pymysql'
 USERNAME: 'root'
 PASSWORD: '2292558Huawei'
 HOST: '127.0.0.1'
 PORT: '3306'
 DATABASE: 'agentscope'
 #服务URL
 SERVICE_URL: 'http://106.74.31.170:5003/plugin/api'